### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by diomed** [OwlyStuff/amazium#144]
hello

could you please make this available for use through unpkg CDN

https://unpkg.com

**Comment by catchamonkey** [comment]
Happy to receive a PR to look over, but generally i'm not in favour of using CDN's.

Prefer to have assets available with the app, otherwise, if the CDN has problems (yeah it does happen...) then your site has problems that are easily avoidable.

**Comment by diomed** [comment]
but only owner can do this & it's simple: 

> All you need to do is include your UMD build in your npm package (not your repo, that's different!).
> 
> You can do this easily using the following setup:
> 
> Add the umd (or dist) directory to your .gitignore file
> Add the umd directory to your files array in package.json
> Use a build script to generate your UMD build in the umd directory when you publish
> That's it! Now when you npm publish you'll have a version available on unpkg as well.

**Comment by catchamonkey** [comment]
We publish to npm using a travis release which is configured in the repo.
So anything to do with that _can_ be configured in the repo via a PR :)

We don't publish manually, it's all automated to keep things simple, consistent and reproducible.

**Comment by hobnob** [comment]
As stated on the unpkg website @diomed:

> unpkg is a fast, global content delivery network for **everything on npm**

(emphasis mine)

This means that Amazium is automatically included by this CDN, because we already use a `dist` folder.

As @catchamonkey stated it is our preference that you have assets stored with your library in case the CDN experiences issue.

However, if you don't wish to do this I have taken the liberty of searching for Amazium on Unpkg for you, and it can be found here:
https://unpkg.com/amazium/dist/amazium.css

Hope this helps :)
