### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fmunizm** [OwlyStuff/Amazium#54]
Thank you for this instructions Catchamonkey. I'm reading this now and I believe that this solution is very good for my need. ,

P2or, I'm using the forms.html as sample. But, i can't create or change the validation options?i.e. I need to verify the password lenght, if the confirmation password is equal to password, the text fields lenght... and I want to show the Amazium messages, as a red bar (tag small). Its a beautifull solution.

PS.: Sorry. Idon't know how can I reopen another issue.

Thank you all!!

**Comment by catchamonkey** [comment]
Hi @fmunizm 
I think this is really something you need to look more into, you need to do 'complex' validation like password == password in the language handling the submissions. Be that Ruby, PHP, etc.
It's not an issue that Amazium can help with, as it's a CSS framework. That's why I closed the issue.
